# Generated by Django 2.0.7 on 2020-04-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='start_date',
            field=models.TextField(),
        ),
    ]
